version: '3.8'

services:
  api:
    build:
      context: ./backend-api-dotnet6/Web
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  bff:
    build:
      context: ./bff-gateway
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend-react
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  blazor:
    build:
      context: ./blazor-frontend-server
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
